"""
Pydantic models for email clustering data structures.
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class EmailData(BaseModel):
    """Email data for clustering."""

    email_id: int
    sender: str
    subject: str
    body: str
    sent_at: datetime


class EmbeddingData(BaseModel):
    """Embedding data with metadata."""

    email_id: int
    embedding: list[float]
    model: str = Field(default="text-embedding-3-small")
    dimension: int = Field(default=1536)


class ClusterPoint(BaseModel):
    """3D point with cluster assignment."""

    email_id: int
    x: float
    y: float
    z: float
    cluster_label: int  # -1 for noise in DBSCAN
    subject: str
    sender: str


class ClusterLabel(BaseModel):
    """Cluster label generated by GPT."""

    cluster_id: int
    cluster_label: int
    short_label: str
    description: str
    num_emails: int
    sample_count: int


class ClusterMetadata(BaseModel):
    """Complete cluster metadata."""

    cluster_id: int
    persona_id: int
    cluster_label: int
    short_label: Optional[str] = None
    description: Optional[str] = None
    num_emails: int
    centroid_x: Optional[float] = None
    centroid_y: Optional[float] = None
    centroid_z: Optional[float] = None
    color: Optional[str] = None  # For visualization
    created_at: datetime


class PersonaIndexStatus(BaseModel):
    """Status of persona email indexing."""

    persona_id: int
    persona_name: str
    total_emails: int
    indexed_at: Optional[datetime] = None
    embedding_model: str = "text-embedding-3-small"
    status: str  # 'indexing', 'completed', 'failed'
    error_message: Optional[str] = None


class IndexingProgress(BaseModel):
    """Progress of ongoing indexing operation."""

    persona_id: int
    status: str
    current_step: str
    progress_percent: float
    total_emails: int
    processed_emails: int
    error_message: Optional[str] = None


class VisualizationData(BaseModel):
    """Complete visualization data for frontend."""

    persona_id: int
    persona_name: str
    points: list[ClusterPoint]
    clusters: list[ClusterMetadata]
    statistics: dict
    indexed_at: datetime


class EmailDetail(BaseModel):
    """Detailed email information for modal display."""

    email_id: int
    sender: str
    recipients_to: list[str]
    recipients_cc: list[str] = Field(default_factory=list)
    recipients_bcc: list[str] = Field(default_factory=list)
    subject: str
    body: str
    sent_at: datetime
    thread_id: Optional[str] = None
    cluster_label: Optional[int] = None
    cluster_name: Optional[str] = None


class ClusterSample(BaseModel):
    """Sample email from a cluster for labeling."""

    email_id: int
    subject: str
    body: str
    # Truncate body to first 500 characters for GPT labeling

    @property
    def truncated_body(self) -> str:
        """Return truncated body for API calls."""
        max_length = 500
        if len(self.body) > max_length:
            return self.body[:max_length] + "..."
        return self.body
